version: '3.5'

services:
  postgres_main:
    container_name: global_search_postgres_container_main
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-public}
      PGDATA: /data/postgres_main
    ports:
      - "5532:5432"
    networks:
      - global-search
    restart: unless-stopped
  postgres_si:
    container_name: global_search_postgres_container_si
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-public}
      PGDATA: /data/postgres_si
    ports:
      - "5533:5432"
    networks:
      - global-search
    restart: unless-stopped
  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:1.3.8
    environment:
      - cluster.name=search-cluster
      - node.name=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - plugins.security.ssl.http.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - global-search
    restart: unless-stopped
  opensearch-dashboards:
    container_name: opensearch-dashboards
    image: opensearchproject/opensearch-dashboards:1.3.8
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - opensearch.username="admin"
      - opensearch.password="admin"
    depends_on:
      - opensearch
    networks:
      - global-search

networks:
  global-search:
    driver: bridge

volumes:
  postgres:
