### Настройки DevSecOps ###
### https://confluence.sberbank.ru/pages/viewpage.action?pageId=134512581 Краткий гайд по использованию Checkmarx ###
### https://confluence.sberbank.ru/pages/viewpage.action?pageId=904831482 Разбор потенциально уязвимых библиотек в SALM ###

### Общая информация о команде ###
team:
  - {
    # Код ЕАСУП команды в МУССе
    # Ссылка на МУСС пром: http://sbergile.sbt-life.sberbank.ru/squads
    mus_code: "00170025",
    # название команды в МУССе
    mus_name: "DevOops",
    # почтовый адрес Product Owner в МУСе для уведомлений с результатами сканирования. Возможно указание нескольких email через ;
    mus_po_mail: "Morozov.E.Se@sberbank.ru, Agapov.D.Vl@sberbank.ru",
  }
#  - {
#      # Вторую и последующие команды необходимо добавить по формату, аналогично первой
#      mus_code: "00040018",
#      # название команды в МУССе
#      mus_name: "Web SBOL Design",
#      # почтовый адрес Product Owner в МУССе для уведомлений с результатами сканирования. Возможно указание нескольких email через ;
#      mus_po_mail: "sspetrov@sberbank.ru",
#    }

### Общая информация о приложении ###
app:
  # конфигурационный элемент КЭ приложения / модуля ПО в Service Manager
  sm_id: "149046"
  # название КЭ приложения / модуля ПО в Service Manager
  sm_name: "ППРБ Каркас СберБизнес"
### Настройки SAST Checkmarx ###
sast_cx:
  # сredentials id в Jenkins для учетной записи Checkmarx одной команды, под которой будет проводиться сканирование
  creds_id: "MUS_00170025-secman"
  # проектная область в JIRA для заведения и синхронизации дефектов
  jira_area: "DCBDEVOPS"
  # маски файлов и директорий для включения (**/*) в скан и исключения (!**/*) из скана
  masks: "!**/.idea/*, !**/config/*, !**/docker/*, !**/gradle/*, !**/jenkins/*, !**/openshift/*, !**/sowa/*, **/*.java, **/*.groovy, **/*.py, **/*.html, **/*.css, **/*.less, **/*.js, **/*.jsx, **/*.ts, **/*.jsp, **/*.sql, !**/js/base-libs/**/*, !**/js/libs/**/*, !**/styles/_vendor/**/*, !**/stub/**/*, !**/generated/**/*, !**/node_modules/**/*, !**/build/**/*, !**/target/**/*, !**/src/test/**/*, !**/tests/**/*, !**/.pipeline/**/*, !**/_cvs/**/*, !**/.svn/**/*, !**/.hg/**/*, !**/.md/**/*, !**/.md, !**/.git/**/*, !**/.bzr/**/*, !**/bin/**/*, !**/obj/**/*, !**/backup/**/*, !**/.idea/**/*, !**/pom.xml, !**/*.DS_Store, !**/*.gradle, !**/*.ipr, !**/*.iws, !**/*.bak, !**/*.tmp, !**/*.aac, !**/*.aif, !**/*.iff, !**/*.m3u, !**/*.mid, !**/*.mp3, !**/*.mpa, !**/*.ra, !**/*.wav, !**/*.wma, !**/*.3g2, !**/*.3gp, !**/*.asf, !**/*.asx, !**/*.avi, !**/*.flv, !**/*.mov, !**/*.mp4, !**/*.mpg, !**/*.rm, !**/*.swf, !**/*.vob, !**/*.wmv, !**/*.bmp, !**/*.gif, !**/*.jpg, !**/*.png, !**/*.psd, !**/*.tif, !**/*.swf, !**/*.jar, !**/*.zip, !**/*.rar, !**/*.exe, !**/*.dll, !**/*.pdb, !**/*.7z, !**/*.gz, !**/*.tar.gz, !**/*.tar, !**/*.gz, !**/*.ahtm, !**/*.ahtml, !**/*.fhtml, !**/*.hdm, !**/*.hdml, !**/*.hsql, !**/*.ht, !**/*.hta, !**/*.htc, !**/*.htd, !**/*.war, !**/*.ear, !**/*.htmls, !**/*.ihtml, !**/*.mht, !**/*.mhtm, !**/*.mhtml, !**/*.ssi, !**/*.stm, !**/*.stml, !**/*.ttml, !**/*.txn, !**/*.xhtm, !**/*.xhtml, !**/*.class, !**/*.iml, !**/*.sh, !**/*.bat, !Checkmarx/Reports/*.*, !**/testdata/**/*, !**/testQuery/**/*, !**/rest-test/**/*"
  # id профиля сканирования, по умолчанию 36. 14 - для мобильного приложения. 100003 - Smoke
  preset_id: "36"
  ###
  # макс время ожидания статуса QG в минутах
  wait_qg: "0"

### Настройки OSS
oss:
  # Маски файлов и директорий для исключения из сканирования
  # Пример: "**/utils/**/*.xml" - исключение всех xml файлов во всех папках utils
  # !!! Перечисление нескольких масок возможно через знаки "," или ";" внутри одной строки, например, "**/*test*/**; **/*.txt, .git/**" !!!
  # !!! Пропуски в каждой маске справа и слева автоматически удалятся (trim) !!!
  excludes: "**/.gradle/**, **/gradle/**"
