server:
  port: 8082

app:
  kafka:
    indexing:
      bootstrap-servers: localhost:9092
      consumer:
        topic: global-search-indexing-topic
        group-id: global-search-indexing-group-id
