---
integration_entries:
  - "{{ int.pprb.appjournal.v1_0 }}"
  - "{{ int.pprb.db_main.v1_0 }}"
  - "{{ int.pprb.db_si.v1_0 }}"
  - "{{ int.sbbol.rest_in.latest }}"
  - "{{ int.pprb.fluentbit.v1_0 }}"
  - "{{ int.pprb.dog900.v1_0 }}"
  - "{{ int.pprb.audit.v1_0 }}"
  - "{{ int.pprb.CI02745214_digitalapi.v1_0 }}"

int_entry:
  pprb:
    audit: "{{ int.pprb.audit.v1_0 }}"
    digitalapi: "{{ int.pprb.CI02745214_digitalapi.v1_0 }}"
  sbbol:
    rest_in: "{{ int.sbbol.rest_in.latest }}"
  ott: "{{ int.ott.v2_0 }}"
